"""Pydantic models for structured LLM outputs.

These models define the expected JSON schema for each pipeline's LLM response.
They enforce structure and enable validation of LLM outputs before processing.
"""

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Topic Extraction
# ---------------------------------------------------------------------------
class ExtractedTopic(BaseModel):
    """A topic extracted from a journal entry by the LLM."""

    name: str = Field(..., description="Specific topic name (e.g. 'Go concurrency patterns')")
    description: str = Field(..., description="Brief description of the topic")
    category: str = Field(
        ...,
        description="One of: demonstrated_strength, weak_spot, current_frontier, "
        "next_frontier, recurring_theme, unresolved",
    )
    evidence_strength: str = Field(..., description="One of: strong, developing, limited")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in the assessment")
    reasoning: str = Field(..., description="Explanation of why this topic was identified")


class TopicExtractionResult(BaseModel):
    """Structured output from the topic extraction pipeline."""

    topics: list[ExtractedTopic] = []
    relationships: list[dict] = Field(default=[], description="Topic adjacencies and prerequisites")


# ---------------------------------------------------------------------------
# Quiz Generation
# ---------------------------------------------------------------------------
class GeneratedQuestion(BaseModel):
    """A quiz question generated by the LLM."""

    question_text: str
    question_type: str = Field(..., description="'reinforcement' or 'exploration'")
    target_topic: str = Field(..., description="Topic this question targets")
    difficulty_rationale: str = Field(..., description="Why this difficulty level")
    reference_answer: str = Field(
        default="",
        description=(
            "Model answer the user will see after they submit their own "
            "response. Should be a concise but substantive paragraph that "
            "demonstrates a strong answer. May be empty for legacy responses."
        ),
    )


class QuizGenerationResult(BaseModel):
    """Structured output from quiz generation."""

    questions: list[GeneratedQuestion] = []


# ---------------------------------------------------------------------------
# Quiz Evaluation
# ---------------------------------------------------------------------------
class QuestionEvaluation(BaseModel):
    """LLM evaluation of a single quiz answer."""

    question_id: str
    correctness: str = Field(..., description="'full', 'partial', or 'incorrect'")
    depth_assessment: str = Field(..., description="Assessment of answer depth and nuance")
    explanation: str = Field(..., description="What was right, wrong, or missing")
    confidence: float = Field(..., ge=0.0, le=1.0)
    topic_signals: list[str] = Field(
        default=[], description="Topics the answer reveals knowledge about"
    )


class QuizEvaluationResult(BaseModel):
    """Structured output from quiz evaluation."""

    evaluations: list[QuestionEvaluation] = []
    triage_items: list[dict] = Field(default=[], description="Items requiring user attention")


# ---------------------------------------------------------------------------
# Reading Generation
# ---------------------------------------------------------------------------
class GeneratedReading(BaseModel):
    """A reading recommendation generated by the LLM."""

    title: str
    url: str
    source_domain: str
    description: str
    recommendation_type: str = Field(
        ..., description="'next_frontier', 'weak_spot', or 'deep_dive'"
    )
    target_topic: str
    rationale: str


class ReadingGenerationResult(BaseModel):
    """Structured output from reading generation."""

    recommendations: list[GeneratedReading] = []


# ---------------------------------------------------------------------------
# Project Generation
# ---------------------------------------------------------------------------
class GeneratedProjectFile(BaseModel):
    """A single file in a generated Go project."""

    path: str = Field(..., description="Relative file path (e.g. 'main.go')")
    content: str = Field(..., description="File content")


class GeneratedProjectTask(BaseModel):
    """A task within the generated project."""

    title: str
    description: str
    task_type: str = Field(..., description="'bug_fix', 'feature', 'refactor', or 'optimization'")


class ProjectGenerationResult(BaseModel):
    """Structured output from project generation."""

    title: str
    description: str
    readme_content: str
    files: list[GeneratedProjectFile] = []
    tasks: list[GeneratedProjectTask] = []
    difficulty_level: int = Field(..., ge=1, le=10)


# ---------------------------------------------------------------------------
# Project Evaluation
# ---------------------------------------------------------------------------
class TaskEvaluation(BaseModel):
    """Evaluation of a single project task."""

    task_title: str
    completed: bool
    quality_notes: str
    score: float = Field(..., ge=0.0, le=1.0)


class ProjectEvaluationResult(BaseModel):
    """Structured output from project evaluation."""

    code_quality_score: float = Field(..., ge=0.0, le=1.0)
    task_evaluations: list[TaskEvaluation] = []
    test_results_summary: str
    overall_assessment: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    difficulty_adjustment: int = Field(..., description="Suggested difficulty change: -1, 0, or +1")
    triage_items: list[dict] = Field(default=[], description="Items requiring user attention")
